version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - ENVIRONMENT=production
      - HOST=0.0.0.0
      - PORT=8000
      - WORKERS_PER_CORE=1
      - WEB_CONCURRENCY=4
      - LOG_LEVEL=info
      - ALLOWED_ORIGINS=https://yourdomain.com
      - RATE_LIMIT_GENERAL=100/minute
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    volumes:
      - ./app.log:/app/app.log 