networks:
  api-network:
    driver: bridge
    internal: false  # Set to true if your service doesn't need internet access
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PYTHON_VERSION: "3.11"
    image: hello-world-api:${IMAGE_TAG:-latest}
    container_name: hello-world-api
    # Set init: true to use an init process that properly handles signals
    init: true
    # Use stop_grace_period to ensure clean shutdown
    stop_grace_period: 30s
    ports:
      # Bind only to localhost in non-production environments
      - "127.0.0.1:8000:8000"
    env_file:
      - .env
    environment:
      - ENVIRONMENT=development
      - HOST=0.0.0.0
      - PORT=8000
      - WORKERS=4
      - LOG_LEVEL=INFO
      - ALLOWED_ORIGINS=*
      - RATE_LIMIT_GENERAL=100/minute
    restart: unless-stopped  # Better than 'always' as it won't restart if stopped manually
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
        compress: "true"
    healthcheck:
      test: ["CMD", "/app/healthcheck.sh"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    # Set resource limits to prevent container from consuming too many resources
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 128M
    # Security options
    security_opt:
      - no-new-privileges:true  # Prevent privilege escalation
    # Read-only root filesystem for added security
    # Note: We need to mount specific directories as writable
    read_only: true
    tmpfs:
      - /tmp:exec,mode=1777
    networks:
      - api-network