apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-world-api-config
  labels:
    app: hello-world-api
data:
  ENVIRONMENT: "production"
  HOST: "0.0.0.0"
  PORT: "8000"
  WORKERS: "2"
  LOG_LEVEL: "INFO"
  ALLOWED_ORIGINS: "*"
  RATE_LIMIT_GENERAL: "100/minute" 